# .github/release.yml
# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: 🏕 Features
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
          - chore
          - bug
    - title: 🛠 Fixes
      labels:
        - bug
    - title: 🧹 Maintenance
      labels:
        - chore
    - title: 👒 Dependencies
      labels:
        - dependencies