name: "PR Title Checker"
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
    contents: read
    pull-requests: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: thehanimo/pr-title-checker@v1.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false

      - name: add bug label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ contains(github.event.pull_request.title, 'bugfix:') }}
        with:
          labels: bug

      - name: add chore label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ contains(github.event.pull_request.title, 'chore:') }}
        with:
          labels: chore

      - name: add feature label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ contains(github.event.pull_request.title, 'feat:') }}
        with:
          labels: feature