name: "PR Title Checker"
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
    contents: read
    pull-requests: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: karpikpl/pr-title-checker@main
        id: check
        continue-on-error: true
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false

      - name: clean labels
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          fail_on_error: false
          labels: |
            bug
            chore
            feature

      - name: add bug label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ contains(github.event.pull_request.title, 'bugfix:') }}
        with:
          labels: bug

      - name: add chore label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ contains(github.event.pull_request.title, 'chore:') }}
        with:
          labels: chore

      - name: add feature label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ contains(github.event.pull_request.title, 'feat:') }}
        with:
          labels: feature
      
      - name: Add comment to fix PR title
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ steps.check.outputs.success == 'false'}}
        with:
          header: 'PR Title Check'
          recreate: true
          message: |
              ### 🚨 PR Title Needs Formatting 🚨
              The title of this PR needs to be formatted correctly and include an Azure Boards Reference. 
              Please update the title to match the format `type: description AB#xxx`. Examples:
              * `bugfix: fix typo in README.md AB#123`
              * `chore: update dependencies AB#456`
              * `feat: add new feature AB#789`
              * `chore: fixing build pipeline` - no AB reference

      - name: Add comment that PR title is fixed
        if: ${{ steps.check.outputs.success == 'true'}}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: 'PR Title Check'
          recreate: true
          message: |
              ### ✅ PR Title Fixed ✅
              The title of this PR has been updated to match the correct format. Thank you!       
      
      - name: Fail if PR title is incorrect
        if: ${{ steps.check.outputs.success == 'false'}}
        run: exit 1