name: Update Release Notes

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
        releaseId: 
            description: 'The Id of the release to update - database Id (integer), not visible in the UI'
            required: true
            type: number

permissions:
  contents: write

jobs:
  update-release-notes:
    runs-on: ubuntu-latest

    steps:

      - name: Install dependencies
        run: npm install node-fetch

      - name: Update release notes
        uses: karpikpl/azdo-relese-notes-action@v1.0.0
        with:
          ado-pat: ${{ secrets.ADO_PAT }}
          ado-org: ${{ vars.ADO_ORG }}
          ado-project: ${{ vars.ADO_PROJECT }}
